apiVersion: v1
kind: Service
metadata:
  name: catalog-app-service
spec:
  selector:
    application: catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer