apiVersion: v1
kind: Service
metadata:
  name: catalog-db-service
spec:
  selector:
    application: catalog-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP